export const Beth: IRoDPlayable = {
	name: 'Beth',
	displayName: 'Beth',
	artists: ['xvi'],
	class: 'Villager',
	affinity: 'Dark',
	description: 'Young and pragmatic villager looking for a way to move up in the world. Always taught to get her hands dirty if needed.',
	classDesc: 'The lance itself stood taller than her, but looking at her you\'d know she was liable to slay giants twice her height.',
	fullName: 'Bethelyn Tiller',
	pronouns: 'She/Her',
	height: '5\'1\"',
	age: 14,
	hobby: 'Eavesdropping',
	birthday: 'June 15',
	promo: 'Starosta',
	promoDesc: 'Klaudia handed her the cuirass and shook her hand, and at long last her efforts had finally borne fruit.',
}
