export const Emerson: IRoDPlayable = {
	name: 'Emerson',
	displayName: 'Emerson',
	artists: ['levin'],
	class: 'Bow Armor',
	affinity: 'Light',
	description: 'Wandering hedge knight currently working in Meraly. Their unusual armaments are a tribute to their martyred parents.',
	classDesc: 'Determined to prove them all wrong. For every enemy with an arrow-hole in the chest, their point is made better.',
	fullName: 'Wesley Emerson',
	pronouns: 'They/She/He',
	height: '5\'5\"',
	age: 21,
	hobby: 'No time for that.',
	birthday: 'September 4',
	promo: 'Juggernaut',
	promoDesc: 'Proved them all wrong. Mastery of lances and bows turns them into an all-ranged solo enemy decimator.',
}
