export const Josephine: IRoDPlayable = {
	name: 'Josephine',
	displayName: 'Josephine',
	artists: ['meatOfJustice'],
	class: 'Mage Armor',
	//affinity: 'Wind',
	description: 'Royal knight in service to House Ouahed. To cope with her dashed dreams, her wit spits venom in the verses she composes.',
	classDesc: 'Refused the traditional weapons of knighthood, claiming weaving spells was the only way to preserve sanity.',
	fullName: 'Josephine Ventadorn',
	pronouns: 'She/They',
	height: '5\'8\"',
	age: 28,
	hobby: 'Composing poetry',
	birthday: 'January 20',
	promo: 'Thaumachine',
	promoDesc: 'Mana coursed the plates, crackling energy searing all nearby, as she lamented that it could be different.',
}
