export const Zero: IRoDPlayable = {
	name: 'Zero',
	displayName: 'Zero',
	artists: ['dragz'],
	class: 'Runelord',
	affinity: 'Thunder',
	description: 'Lord Ouahed\'s principal retainer. Cold and aloof, he\'s content to remain as the dagger always at his lord\'s side.',
	classDesc: 'Light glinted off the blade as it was drawn: a flash of blood, a stolen gem, and a slink back into to the shadows.',
	fullName: '\'Zero\' Roth',
	pronouns: 'He/Him',
	height: '5\'9\"',
	age: 49,
	hobby: 'Throwing knives',
	birthday: 'July 29',
	promo: '',
	promoDesc: '',
}
