import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import '@dream-of-components/react/index.esm.css'
import { RoDArtistConfig } from "@rod/config"
import { getArtistCreditStyles } from '@dream-of-components/react';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className} style={getArtistCreditStyles(RoDArtistConfig)}>{children}</body>
    </html>
  )
}
